### PR TITLE
Add function to map MIME types to file extensions

### PR DESCRIPTION
**Pull request by DolphinChips**

### CODE REVIEW

**Comment by dinosaure** [comment]
Hi, thanks for your PR :+1:. Did you know that we prefer to use [`conan`](https://github.com/mirage/conan) which is more complete and up to date than `ocaml-magic-mime`? IF you have some constraints about this package, we are able to introduce your PR and cut a release if you want. But be aware that this package will be less and less maintained.

**Comment by DolphinChips** [comment]
> Hi, thanks for your PR +1. Did you know that we prefer to use [`conan`](https://github.com/mirage/conan) which is more complete and up to date than `ocaml-magic-mime`? IF you have some constraints about this package, we are able to introduce your PR and cut a release if you want. But be aware that this package will be less and less maintained.

Hi, thanks for replying! I was aware of `conan`, but I wasn't aware that it's preferred over `ocaml-magic-mime`. However, it doesn't include a complete MIME type database (or I just can't find it), so I'll need this library and its database anyways.

If you are curious, what my application does is packing up a bunch of WordPress pages and theirs content into ePub. Some images hosted have mismatching file extension and actual content (like JPEG with .webp). While I could just declare correct MIME type from `Content-Type` header, [`epubcheck`](https://www.w3.org/publishing/epubcheck/) will still complain to me, so I use this library with this PR applied to map MIME type to whatever file extension I need to use. `conan` wouldn't help me with this because it gives me a MIME type and not a file extension :\

**Comment by DolphinChips** [comment]
Also, If you introduce this functionality in `conan`, I will happily use it instead (:

**Comment by dinosaure** [comment]
Thanks and sorry for the delay!

**Comment by dinosaure** [comment]
Just to alert that currently `conan` (the _upstream_ version) implement too such map from the database.

**Pull request merged**
